folder: results/imagenet/vqvae
num_hiddens: 128
num_residual_layers: 2
num_residual_hiddens: 32
num_embeddings: 512
embedding_dim: 64
commitment_cost: 0.25
decay: 0.99
stride: 8
upsample_method: bilinear

image_size: 128
nb_channels: 3
train_dataset_folder: data/imagenet-lmdb/train
dataset_type: lmdb
nb_examples: 100000

batch_size: 128
num_workers: 4
weight_decay: 0
scheduler_gamma: 1
lr: 0.0005
epochs: 1000
gpus: 1
distributed_backend: dp

perceptual_loss: vgg19
