vqvae_model_path: "results/imagenet05AUG/vqvae/logs/version_1/checkpoints/epoch=28.ckpt"
folder: results/test/transformer
epochs: 1000
lr: 0.00001
weight_decay: 0
learning_rate_scheduler: null
batch_size: 8
num_workers: 0
gpus: 1
distributed_backend: dp
nb_examples: 1000
save_every: 1
generate: false
hidden_size: 768
num_hidden_layers: 8
num_attention_heads: 8
intermediate_size: 6144
hidden_dropout_prob: 0
attention_dropout_prob: 0
gradient_clip_val: 1 #0=don't clip
warmup_iter: 0
fixed_encoder: False
