folder: results/test
num_hiddens: 128
num_residual_layers: 2
num_residual_hiddens: 128
num_embeddings: 512
embedding_dim: 128
commitment_cost: 0.25
decay: 0.99
stride: 8
upsample_method: bilinear

image_size: 256
nb_channels: 3

train_dataset_folder: data/imagenet-lmdb/train
dataset_type: lmdb

nb_examples: 10000

batch_size: 32
num_workers: 48 
weight_decay: 0
scheduler_gamma: 1
lr: 0.0001
epochs: 1000
gpus: 4
distributed_backend: dp
save_every: 1
perceptual_loss: vgg19
