vqvae_model_path: results/srgan/vqvae/model.th
folder: results/srgan/generator
epochs: 10000
lr: 0.0001
weight_decay: 0
scheduler_gamma: 1
batch_size: 8
num_workers: 0
gpus: 1
distributed_backend: horovod
nb_examples: null
save_every: 1

hidden_size: 768
num_hidden_layers: 6
num_attention_heads: 6
intermediate_size: 3072
hidden_dropout_prob: 0.0
attention_dropout_prob: 0.0
