vqvae_model_path: "results/imagenet05AUG/vqvae/logs/version_1/checkpoints/epoch=28.ckpt"
folder: results/imagenet20AUG/transformer
epochs: 500
lr: 0.000005
weight_decay: 0
learning_rate_scheduler: null
batch_size: 4
num_workers: 0
gpus: 1
distributed_backend: horovod
nb_examples: 100000
save_every: 1
generate: false
hidden_size: 768
num_hidden_layers: 12
num_attention_heads: 12
intermediate_size: 6144
hidden_dropout_prob: 0
attention_dropout_prob: 0
gradient_clip_val: 1 #0=don't clip
warmup_iter: 15640
warmup_ratio: null
#warmup_ratio: 0.2
fixed_encoder: False
