folder: results/imagenet05AUG/vqvae
num_hiddens: 128
num_residual_layers: 2
num_residual_hiddens: 128
num_embeddings: 512
embedding_dim: 128
commitment_cost: 1
decay: 0.99
stride: 4
upsample_method: bilinear

image_size: 96
nb_channels: 3

train_dataset_folder: data/imagenet-lmdb/train
dataset_type: lmdb

#train_dataset_folder: ../../data/imagenette-160/train/
#dataset_type: image_folder

#train_dataset_folder: data/celebahq/256
#dataset_type: image_folder

nb_examples: null

batch_size: 128

num_workers: 0
weight_decay: 0
scheduler_gamma: 1
lr: 0.0001
epochs: 1000
gpus: 1
distributed_backend: horovod
save_every: 1
perceptual_loss: vgg19
perceptual_loss_resize: False
