folder: out/vqvae

num_hiddens: 128
num_residual_layers: 2
num_residual_hiddens: 32
num_embeddings: 512
embedding_dim: 64
commitment_cost: 0.25
decay: 0.99
stride: 4

image_size: 128
nb_channels: 3
train_dataset_folder: data/imagenette-160/train
nb_examples: null

batch_size: 256
num_workers: 0
weight_decay: 0
scheduler_gamma: 1
lr: 0.0005
epochs: 300
gpus: 0
